# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='log_reg.User'),
        ),
    ]
